version: '3.0'
services: 
 webapp:
        build: "node8/"
        hostname: "node1"
        volumes:
            -  ./server:/servidor:rw
            -  ./cliente:/cliente:rw



        networks:
            webappv2:
                ipv4_address: 192.168.70.44


networks:
  webappv2:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 192.168.70.0/24
        gateway: 192.168.70.1
