services:
  pbase_db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - db_ma:/var/lib/mysql  # Corregido: Sin espacio después de los ":"
    ports:
      - "3366:3306"
    networks:
      webappv2:
        ipv4_address: 192.168.70.45

  webapp: # Corregido: Ahora está bien indentado bajo "services"
    build:
      context: "."
      dockerfile: "node8/Dockerfile"
    hostname: "node1"
    ports:
      - "3000:3000"
      - "8080:8080"
      - "9229:9229"
    networks:
      webappv2:
        ipv4_address: 192.168.70.44

volumes:
  db_ma:

networks:
  webappv2:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.70.0/24
          gateway: 192.168.70.1