version: '3.0'
services: 
 webapp:
        build: "node8/"
        hostname: "node1"
        expose:
              - "8080"
              - "3000"
        volumes:
            -  ./server:/opt/server:rw
            -  ./cliente:/opt/cliente:rw



        networks:
            webapp:
                ipv4_address: 172.23.18.10


networks:
  webapp:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.23.18.0/16
        gateway: 172.23.18.1
